---
name: Steam Stats
on:
  push:
    branches: main
  # schedule:
  #   - cron: 30 18 * * 0
  workflow_dispatch: null
jobs:
  steam-stats:
    name: Steam Stats
    runs-on: ubuntu-latest
    steps:
      - uses: nicconike/steam-stats@master
        with:
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
          STEAM_ID: ${{ vars.STEAM_ID }}
          STEAM_CUSTOM_ID: ${{ vars.STEAM_CUSTOM_ID }}
          LOG_SCALE: True
